add Delete/Overwrite named regions functionality v2
ycphs/openxlsx pull request #251
Opened 2021-08-27 14:22 UTC by bthieurmel

Without the white space changes...!

2021-08-27 14:44 UTC, JanMarvin requested changes
Looks good, minor changes, but please add the missing documentation and a test.

2021-08-27 14:44 UTC, JanMarvin commented on R/wrappers.R
> +    warning(sprintf("Canno't  find Named region with name '%s'", name))
Typo

2021-08-27 14:44 UTC, JanMarvin commented on R/wrappers.R
> +    stop(sprintf("Named region with name '%s' already exists! Use overwrite  = TRUE if you want to replace it", name))
double whitespace

2021-08-27 14:44 UTC, JanMarvin commented on R/wrappers.R
> +#' @export
Could you add some text to the function for the man-page. What it does and and an example how the code runs. Currently it fails the check.

2021-09-01 10:40 UTC, bthieurmel commented
Done

2021-09-01 13:11 UTC, JanMarvin commented on R/wrappers.R
> +    warning(sprintf("Canno't find Named region with name '%s'", name))
should be "Cannot",  "Can not" or "Can't": smile

2021-09-01 13:13 UTC, JanMarvin commented
Thanks!

2021-09-01 21:41 UTC, JanMarvin approved these changes

2021-09-02 11:41 UTC, merged