Bug #330: writeData with a date creates a new number format style, which potentially needs a unique number format ID
ycphs/openxlsx pull request #331
Opened 2022-02-23 01:32 UTC by kainhofer

Make sure that writeData with a date creates a style that has no collisions of its numFmtId with existing styles. By default, a style with numFmdId=165 (hard-coded!) is created by createStyle. When inserting that style into a workbook, we need to assign it a new, unique numFmtId if the workbook already has some custom number formats.
The explicitly-called addStyle function checked for this case, but the implicitly-called classStyles function did not.

Fixes #330.

2022-02-23 11:58 UTC, JanMarvin commented
If you could fix the tests we can merge this. It's rather small, a test would be an additional benefit as well as checks for dups in numfmtid, but these are optional. So long nobody has complained and the package is around for a long time :-)
Some entry in NEWS.md would be nice.

2022-02-23 11:58 UTC, JanMarvin requested changes
Unittests fail.

2022-03-08 07:31 UTC, mgross-ebner commented
> If you could fix the tests we can merge this. It's rather small, a test would be an additional benefit as well as checks for dups in numfmtid, but these are optional. So long nobody has complained and the package is around for a long time :-) Some entry in NEWS.md would be nice.

Dear Jan, just for the sake of completeness, let me mention that we are affected by the problem and are eagerly waiting for a patch. 

Thank you for the super package and your efforts!

Best regards
Markus

2022-04-05 10:12 UTC, ycphs commented
As soon as the unit tests are fixed, we can merge the PR. I totally understand the need you have. If you could provide a fix for the unit tests, we can merge the PR.

I am looking forward for your contribution, @mgross-ebner

2022-04-05 15:05 UTC, kainhofer commented
@ycphs I'm aware of the failing unit tests (and they indicate real problems with the patch, which need to be fixed). 
Unfortunately, I'm currently really short on time, so I can't promise when I'll be able to take a look and fix the issues with the PR.

2022-04-18 21:25 UTC, kainhofer commented
Just fixed the issue with the unit tests. Apparently sapply(list(....), function(x) ...) will return a vector, UNLESS the list is empty, in which case an empty list (and not an empty vector) is returned... That's quite inconsistent behavior of sapply, but can be worked around by a call to unlist to always force sapply to return a vector...

2022-04-19 05:54 UTC, merged